### ISSUE TITLE
getNetworkSuid returns NA

### ISSUE THREAD

**Issue by rmflight** [cytoscape/RCy3#17] opened 2018-04-02 20:29 UTC
R version: 3.5.0
RCy3 version: 1.99.9 (github version)

```
library(graph)
g <- makeSimpleGraph()
createNetworkFromGraph(g)
```

Results in: 

```
Error in getNetworkSuid(network) : Network does not exist: NA
In addition: Warning message:
In getNetworkSuid(network) : NAs introduced by coercion
```

Reason: looks like `getNetworkSuid()` is returning a list of values, even with length [[1]]

**Comment by AlexanderPico** [comment] 2018-04-03 23:01
I could not reproduce this error, but your PR doesn't break anything so I merged it :)

**Closed by AlexanderPico** 2018-04-03 23:01 UTC

**Comment by rmflight** [comment] 2018-04-04 00:15
Huh, interesting. I really wish there was a way to run a headless Cytoscape
instance and run the tests on Travis in addition to locally.

All I know is the Bioconductor version gave me an error about NA, and
running the tests on master also gave the error, hence my PR, as I need
RCy3 to work for my own package.

Could it be dependent on the version of Cytoscape?? I saw a slightly
different error with Cytoscape 3.5.1.

**Comment by AlexanderPico** [comment] 2018-04-04 01:36
Possibly. But since your PR works in both out cases, that’s the way to go. :)

Oh and we want headless to! Been in the works for many years now... not easy with an entrenched Java Swing application, unfortunately...

 - Alex
